export const CREATE_COURSE_CATEGORY_REQUEST = "CREATE_COURSE_CATEGORY_REQUEST";
export const CREATE_COURSE_CATEGORY_SUCCESS = "CREATE_COURSE_CATEGORY_SUCCESS";
export const CREATE_COURSE_CATEGORY_FAIL = "CREATE_COURSE_CATEGORY_FAIL";



export const ALL_COURSE_CATEGORY_REQUEST = "ALL_COURSE_CATEGORY_REQUEST";
export const ALL_COURSE_CATEGORY_SUCCESS = "ALL_COURSE_CATEGORY_SUCCESS";
export const ALL_COURSE_CATEGORY_FAIL = "ALL_COURSE_CATEGORY_FAIL";



export const UPDATE_COURSE_CATEGORY_REQUEST = "UPDATE_COURSE_CATEGORY_REQUEST";
export const UPDATE_COURSE_CATEGORY_SUCCESS = "UPDATE_COURSE_CATEGORY_SUCCESS";
export const UPDATE_COURSE_CATEGORY_FAIL = "UPDATE_COURSE_CATEGORY_FAIL";






export const DELETE_COURSE_CATEGORY_REQUEST = "DELETE_COURSE_CATEGORY_REQUEST";
export const DELETE_COURSE_CATEGORY_SUCCESS = "DELETE_COURSE_CATEGORY_SUCCESS";
export const DELETE_COURSE_CATEGORY_FAIL = "DELETE_COURSE_CATEGORY_FAIL";



export const GET_COURSE_CATEGORY_DETAILS_REQUEST = "GET_COURSE_DETAILS_REQUEST";
export const GET_COURSE_CATEGORY_DETAILS_SUCCESS = "GET_COURSE_DETAILS_SUCCESS";
export const GET_COURSE_CATEGORY_DETAILS_FAIL = "GET_COURSE_DETAILS_FAIL";