export const CREATE_REQUEST = "CREATE_REQUEST";
export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const CREATE_FAIL = "CREATE_FAIL";


export const STUDENT_REQUEST = "STUDENT_REQUEST";
export const STUDENT_SUCCESS = "STUDENT_SUCCESS";
export const STUDENT_FAIL = "STUDENT_FAIL";



export const SINGLE_VIEW_REQUEST = "STUDENT_VIEW_REQUEST";
export const SINGLE_VIEW_SUCCESS = "STUDENT_VIEW_SUCCESS";
export const SINGLE_VIEW_FAIL = "STUDENT_VIEW_FAIL";


export const DELETE_STUDENT_REQUEST = "STUDENT_DELETE_REQUEST";
export const DELETE_STUDENT_SUCCESS = "STUDENT_DELETE_SUCCESS";
export const DELETE_STUDENT_FAIL = "STUDENT_DELETE_FAIL";


export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_FAIL = "UPDATE_STUDENT_FAIL";



export const CREATE_NEW_COURSE_REQUEST = "CREATE_NEW_COURSE_REQUEST";
export const CREATE_NEW_COURSE_SUCCESS = "CREATE_NEW_COURSE_SUCCESS";
export const CREATE_NEW_COURSE_FAIL = "CREATE_NEW_COURSE_FAIL";




export const ALL_STUDENT_COURSE_REQUEST = "ALL_STUDENT_COURSE_REQUEST";
export const ALL_STUDENT_COURSE_SUCCESS = "ALL_STUDENT_COURSE_SUCCESS";
export const ALL_STUDENT_COURSE_FAIL = "ALL_STUDENT_COURSE_FAIL";



export const DELETE_STUDENT_COURSE_REQUEST = "DELETE_STUDENT_COURSE_REQUEST";
export const DELETE_STUDENT_COURSE_SUCCESS = "DELETE_STUDENT_COURSE_SUCCESS";
export const DELETE_STUDENT_COURSE_FAIL = "DELETE_STUDENT_COURSE_FAIL";